# Change these first
owner: papies # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Topfarmacia
    url: https://www.topfarmacia.it
    maxResponseTime: 5000
#  - name: Wikipedia
#    url: https://en.wikipedia.org
#  - name: Hacker News
#    url: https://news.ycombinator.com
#  - name: Test Broken Site
#    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Showing topfarmacia.it real-time status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
